### ISSUE TITLE
Example Site| Deployment

### ISSUE THREAD

**Issue by FrankBeatrice** [curtiscde/hugo-theme-dopetrope#35]
Thanks!

**Comment by curtiscde** [comment]
@FrankBeatrice Looking at your revision history on the issue I can see you had a problem getting the example site working locally.

Is this still an issue for you?

**Comment by biomassives** [comment]
geog@positive:~/wp/hugo/quickstart$ hugo serve
Building sites … ERROR 2018/08/30 16:45:49 Error while rendering "home" in "": template: index.html:14:8: executing "main" at <partial "intro.html"...>: error calling partial: template: partials/intro.html:6:24: executing "partials/intro.html" at <index .Site.Data.hom...>: error calling index: index of untyped nil
ERROR 2018/08/30 16:45:49 Error while rendering "taxonomyTerm" in "": template: _default/list.html:35:6: executing "main" at <partial "footer/inde...>: error calling partial: template: partials/footer/index.html:5:15: executing "partials/footer/index.html" at <partial "footer/rece...>: error calling partial: template: partials/footer/recentposts.html:3:16: executing "partials/footer/recentposts.html" at <index .Site.Data.foo...>: error calling index: index of untyped nil
Total in 16 ms

**Comment by biomassives** [comment]
not sure if its just me..

geog@positive:~/wp/hugo/quickstart$ hugo serve --verbose
=WARN 2018/08/30 16:47:13 No translation bundle found for default language "en"
WARN 2018/08/30 16:47:13 Translation func for language en not found, use default.
WARN 2018/08/30 16:47:13 i18n not initialized, check that you have language file (in i18n) that matches the site language or the default language.
INFO 2018/08/30 16:47:13 Using config file: /home/geog/wp/hugo/quickstart/config.toml
Building sites … INFO 2018/08/30 16:47:13 syncing static files to /
ERROR 2018/08/30 16:47:13 Error while rendering "home" in "": template: index.html:14:8: executing "main" at <partial "intro.html"...>: error calling partial: template: partials/intro.html:6:24: executing "partials/intro.html" at <index .Site.Data.hom...>: error calling index: index of untyped nil
WARN 2018/08/30 16:47:13 template: index.html:14:8: executing "main" at <partial "intro.html"...>: error calling partial: template: partials/intro.html:6:24: executing "partials/intro.html" at <index .Site.Data.hom...>: error calling index: index of untyped nil
ERROR 2018/08/30 16:47:13 Error while rendering "taxonomyTerm" in "": template: _default/list.html:35:6: executing "main" at <partial "footer/inde...>: error calling partial: template: partials/footer/index.html:5:15: executing "partials/footer/index.html" at <partial "footer/rece...>: error calling partial: template: partials/footer/recentposts.html:3:16: executing "partials/footer/recentposts.html" at <index .Site.Data.foo...>: error calling index: index of untyped nil
WARN 2018/08/30 16:47:13 template: _default/list.html:35:6: executing "main" at <partial "footer/inde...>: error calling partial: template: partials/footer/index.html:5:15: executing "partials/footer/index.html" at <partial "footer/rece...>: error calling partial: template: partials/footer/recentposts.html:3:16: executing "partials/footer/recentposts.html" at <index .Site.Data.foo...>: error calling index: index of untyped nil
INFO 2018/08/30 16:47:13 Alias "/categories/page/1/index.html" translated to "categories/page/1/index.html"
INFO 2018/08/30 16:47:13 Alias "/tags/page/1/index.html" translated to "tags/page/1/index.html"
WARN 2018/08/30 16:47:13 [en] Unable to locate layout for "404": [404.html theme/404.html]
Total in 18 ms
Error: Error building site: logged 2 error(s)

**Comment by curtiscde** [comment]
@biomassives Which version of Hugo are you running?

**Comment by joaomnmoreira** [comment]
Hi @curttimson!

```
$ hugo version
Hugo Static Site Generator v0.53 linux/amd64 BuildDate: 2018-12-24T12:58:43Z
```

I'm having some issues getting your theme to work in HUGO with the following error (server doesn't start):

```
$ hugo server -v
INFO 2019/01/14 19:06:01 No translation bundle found for default language "en"
INFO 2019/01/14 19:06:01 Translation func for language en not found, use default.
INFO 2019/01/14 19:06:01 i18n not initialized; if you need string translations, check that you have a bundle in /i18n that matches the site language or the default language.
INFO 2019/01/14 19:06:02 Using config file:
Building sites … INFO 2019/01/14 19:06:02 syncing static files to /
INFO 2019/01/14 19:06:02 Alias "/categories/page/1/index.html" translated to "categories/page/1/index.html"
INFO 2019/01/14 19:06:02 Alias "/tags/page/1/index.html" translated to "tags/page/1/index.html"
ERROR 2019/01/14 19:06:02 render of "home" failed: execute of template failed: template: index.html:14:8: executing "main" at <partial "intro.html"...>: error calling partial: "/home/dmc-tec/Repo/hugo/cpro/themes/hugo-theme-dopetrope/layouts/partials/intro.html:6:24": execute of template failed: template: partials/intro.html:6:24: executing "partials/intro.html" at <index .Site.Data.hom...>: error calling index: index of untyped nil
ERROR 2019/01/14 19:06:02 render of "taxonomyTerm" failed: execute of template failed: template: _default/list.html:35:6: executing "main" at <partial "footer/inde...>: error calling partial: "/home/dmc-tec/Repo/hugo/cpro/themes/hugo-theme-dopetrope/layouts/partials/footer/index.html:3:16": execute of template failed: template: partials/footer/index.html:5:15: executing "partials/footer/index.html" at <partial "footer/rece...>: error calling partial: "/home/dmc-tec/Repo/hugo/cpro/themes/hugo-theme-dopetrope/layouts/partials/footer/recentposts.html:3:16": execute of template failed: template: partials/footer/recentposts.html:3:16: executing "partials/footer/recentposts.html" at <index .Site.Data.foo...>: error calling index: index of untyped nil
Total in 146 ms
Error: Error building site: failed to render pages: render of "taxonomyTerm" failed: execute of template failed: template: _default/list.html:35:6: executing "main" at <partial "footer/inde...>: error calling partial: "/home/dmc-tec/Repo/hugo/cpro/themes/hugo-theme-dopetrope/layouts/partials/footer/index.html:3:16": execute of template failed: template: partials/footer/index.html:5:15: executing "partials/footer/index.html" at <partial "footer/rece...>: error calling partial: "/home/dmc-tec/Repo/hugo/cpro/themes/hugo-theme-dopetrope/layouts/partials/footer/recentposts.html:3:16": execute of template failed: template: partials/footer/recentposts.html:3:16: executing "partials/footer/recentposts.html" at <index .Site.Data.foo...>: error calling index: index of untyped nil
```

Can you help?

Best regards,
João

**Comment by joaomnmoreira** [comment]
Hi @curttimson, problem solved... Moved example_site diretories to where it should be. ;)

Thanks for this theme!
