### ISSUE TITLE
Dopetrope Demo on Hugo website contains 3rd party tracking

### ISSUE THREAD

**Issue by onedrawingperday** [curtiscde/hugo-theme-dopetrope#38]
Hello @curttimson 

I am one of the maintainers of the [Hugo Themes](https://github.com/gohugoio/hugoThemes/) repository.

Recently I audited the Hugo Themes website and it has [come to my attention](https://github.com/gohugoio/hugoThemes/issues/535) that your theme's demo has third party tracking enabled.

```
     \hugo-theme-dopetrope\exampleSite\config.toml:
        [params.settings]
        googleanalytics = "UA-113904582-2"
        disqus = "hugo-dopetrope"
```

To fix this issue please leave the above parameters blank i.e.

```
     \hugo-theme-dopetrope\exampleSite\config.toml:
        [params.settings]
        googleanalytics = ""
        disqus = ""
```

Once you look into this please let me know.

Thank you!

**Comment by curtiscde** [comment]
@onedrawingperday 3rd party references removed from example site. Please review.

https://hugo-theme-dopetrope.netlify.com

**Comment by onedrawingperday** [comment]
Thank you for responding to this issue. Everything looks good!
