### ISSUE TITLE
Home page don't have 6 "My Portfolio" items

### ISSUE THREAD

**Issue by raqueeb** [curtiscde/hugo-theme-dopetrope#41]
In your demo site, 6 "My Portfolio" items are shown. In reality in examplesite, I can't generate it.

**Comment by curtiscde** [comment]
Hi @raqueeb, if this is still an issue for you, can you please provide more information? Are you receiving an error? Which Hugo version are you using?

**Comment by curtiscde** [comment]
@raqueeb I have been able to reproduce this issue by using newer versions of Hugo. To address this, the theme has been updated to use Hugo 0.94.2:

https://github.com/curtiscde/hugo-theme-dopetrope/releases/tag/v4.4.0

I hope this helps - please reopen the issue with more information if this does not resolve it.
